# Site settings
title: The Fabric of Space-Time
email: klewis6@saic.edu
description: > # this means to ignore newlines until "baseurl:"
  All rights reserved.
destination: fabricofspaceti.me
url: "https://fabricofspaceti.me" # the base hostname & protocol for your site
# twitter_username: zealouspress
github_username: kaylalewis

# Build settings
markdown: kramdown
